spring.application.name=halcyon_domain
logging.level.root=INFO

# Spring Profiles
spring.profiles.active=dev

# Security Configuration (for development)
spring.security.user.name=user
spring.security.user.password=pass

#h2 data source config
spring.datasource.url=jdbc:h2:mem:testdb
#use below for file based storage
#spring.datasource.url=jdbc:h2:file:/data/demo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#h2 console config
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console